/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type VerifyBankAccountRequestBody = {
  /**
   * Pre-configured constant values for different environements
   */
  entityId: string;
  /**
   * Program id related to this activity. (310 for penny drop)
   */
  programId: string;
  /**
   * Unique, alphanumeric reference
   *
   * @remarks
   * number. Logic in pre-processing script.
   */
  requestId: string;
  /**
   * Defines mode of validation Options: ANY/ IMPS/
   *
   * @remarks
   * NACH /UPI/ REVERSE/
   * REVERSE_INTENT
   */
  txnType: string;
  /**
   * Name of account holder to validate.
   */
  custName?: string | undefined;
  /**
   * IFSC of bank account to validate. Required if
   *
   * @remarks
   * txnType is other than UPl/ REVERSE
   * / REVERSE_INTENT
   */
  custIfsc?: string | undefined;
  /**
   * Account number to validate. Required if txnType is
   *
   * @remarks
   * other than UPl/ REVERSE
   * / REVERSE_INTENT
   */
  custAcctNo?: string | undefined;
  /**
   * VPA to validate if txnType is UPI
   *
   * @remarks
   * Not Required when txnType=REVERSE_INTENT
   */
  custVpa?: string | undefined;
  /**
   * Mobile number
   *
   * @remarks
   * Required if txnType=UPI and VPA is provided.
   */
  custMobileNo?: string | undefined;
  /**
   * Your system reference number for this user
   */
  trackingRefNo?: string | undefined;
  /**
   * The API endpoint where we will submit updates on
   *
   * @remarks
   * the validation status for each requestld.
   * Required if txnType is REVERSE/
   * REVERSE_INTENT
   */
  callbackUrl?: string | undefined;
};

export type VerifyBankAccountRequest = {
  apikey: string;
  body: VerifyBankAccountRequestBody;
};

export type VerifyBankAccountResponse = {
  statusCode: string;
  status?: string | undefined;
  acValidationStatus?: string | undefined;
  message?: string | undefined;
  requestId?: string | undefined;
  responseId?: string | undefined;
  nameAtBank?: string | undefined;
  custAcctNo?: string | undefined;
  custIfsc?: string | undefined;
  bankCode?: string | undefined;
  methodUsed?: string | undefined;
  custName?: string | undefined;
  custVpa?: string | undefined;
  fuzzylogicScore?: string | undefined;
  utr?: string | undefined;
  qrUrlString?: string | undefined;
};

/** @internal */
export type VerifyBankAccountRequestBody$Outbound = {
  entityId: string;
  programId: string;
  requestId: string;
  txnType: string;
  custName?: string | undefined;
  custIfsc?: string | undefined;
  custAcctNo?: string | undefined;
  custVpa?: string | undefined;
  custMobileNo?: string | undefined;
  trackingRefNo?: string | undefined;
  callbackUrl?: string | undefined;
};

/** @internal */
export const VerifyBankAccountRequestBody$outboundSchema: z.ZodMiniType<
  VerifyBankAccountRequestBody$Outbound,
  VerifyBankAccountRequestBody
> = z.object({
  entityId: z.string(),
  programId: z.string(),
  requestId: z.string(),
  txnType: z.string(),
  custName: z.optional(z.string()),
  custIfsc: z.optional(z.string()),
  custAcctNo: z.optional(z.string()),
  custVpa: z.optional(z.string()),
  custMobileNo: z.optional(z.string()),
  trackingRefNo: z.optional(z.string()),
  callbackUrl: z.optional(z.string()),
});

export function verifyBankAccountRequestBodyToJSON(
  verifyBankAccountRequestBody: VerifyBankAccountRequestBody,
): string {
  return JSON.stringify(
    VerifyBankAccountRequestBody$outboundSchema.parse(
      verifyBankAccountRequestBody,
    ),
  );
}

/** @internal */
export type VerifyBankAccountRequest$Outbound = {
  apikey: string;
  body: VerifyBankAccountRequestBody$Outbound;
};

/** @internal */
export const VerifyBankAccountRequest$outboundSchema: z.ZodMiniType<
  VerifyBankAccountRequest$Outbound,
  VerifyBankAccountRequest
> = z.object({
  apikey: z.string(),
  body: z.lazy(() => VerifyBankAccountRequestBody$outboundSchema),
});

export function verifyBankAccountRequestToJSON(
  verifyBankAccountRequest: VerifyBankAccountRequest,
): string {
  return JSON.stringify(
    VerifyBankAccountRequest$outboundSchema.parse(verifyBankAccountRequest),
  );
}

/** @internal */
export const VerifyBankAccountResponse$inboundSchema: z.ZodMiniType<
  VerifyBankAccountResponse,
  unknown
> = z.object({
  statusCode: types.string(),
  status: types.optional(types.string()),
  acValidationStatus: types.optional(types.string()),
  message: types.optional(types.string()),
  requestId: types.optional(types.string()),
  responseId: types.optional(types.string()),
  nameAtBank: types.optional(types.string()),
  custAcctNo: types.optional(types.string()),
  custIfsc: types.optional(types.string()),
  bankCode: types.optional(types.string()),
  methodUsed: types.optional(types.string()),
  custName: types.optional(types.string()),
  custVpa: types.optional(types.string()),
  fuzzylogicScore: types.optional(types.string()),
  utr: types.optional(types.string()),
  qrUrlString: types.optional(types.string()),
});

export function verifyBankAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<VerifyBankAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerifyBankAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerifyBankAccountResponse' from JSON`,
  );
}
