workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    io-protean:
        inputs:
            - location: ..\io-protean.openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/sandbox-dn/myworkspace/io-protean
targets:
    protean:
        target: typescript
        source: io-protean
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/sandbox-dn/myworkspace/io-protean-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
