/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { proteanVerifyBankAccount } from "../funcs/protean-verify-bank-account.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Protean2 extends ClientSDK {
  /**
   * Bank Account Verification
   *
   * @remarks
   * Verifies Bank Account through Penny Drop, PennyLess and Hybrid.
   */
  async verifyBankAccount(
    request: operations.VerifyBankAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.VerifyBankAccountResponse> {
    return unwrapAsync(proteanVerifyBankAccount(
      this,
      request,
      options,
    ));
  }
}
