/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Protean2 } from "./protean-2.js";

export class Protean1 extends ClientSDK {
  private _protean?: Protean2;
  get protean(): Protean2 {
    return (this._protean ??= new Protean2(this._options));
  }
}
