// This file was auto-generated by Fern from our API Definition.

export interface VerifyBankAccountResponse {
    statusCode: string;
    status?: string | undefined;
    acValidationStatus?: string | undefined;
    message?: string | undefined;
    requestId?: string | undefined;
    responseId?: string | undefined;
    nameAtBank?: string | undefined;
    custAcctNo?: string | undefined;
    custIfsc?: string | undefined;
    bankCode?: string | undefined;
    methodUsed?: string | undefined;
    custName?: string | undefined;
    custVpa?: string | undefined;
    fuzzylogicScore?: string | undefined;
    utr?: string | undefined;
    qrUrlString?: string | undefined;
}
