/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { ProteanError } from "./protean-error.js";

export type ErrorSchemaData = {
  status: boolean;
  errorCode: number;
  errorDescription: string;
};

export class ErrorSchema extends ProteanError {
  status: boolean;
  errorCode: number;
  errorDescription: string;

  /** The original data that was passed to this error instance. */
  data$: ErrorSchemaData;

  constructor(
    err: ErrorSchemaData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.errorCode = err.errorCode;
    this.errorDescription = err.errorDescription;

    this.name = "ErrorSchema";
  }
}

/** @internal */
export const ErrorSchema$inboundSchema: z.ZodMiniType<ErrorSchema, unknown> = z
  .pipe(
    z.object({
      status: types.boolean(),
      error_code: types.number(),
      error_description: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "error_code": "errorCode",
        "error_description": "errorDescription",
      });

      return new ErrorSchema(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
