/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Bank } from "./bank.js";
import { Kyc } from "./kyc.js";

export class Protean extends ClientSDK {
  private _kyc?: Kyc;
  get kyc(): Kyc {
    return (this._kyc ??= new Kyc(this._options));
  }

  private _bank?: Bank;
  get bank(): Bank {
    return (this._bank ??= new Bank(this._options));
  }
}
