// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "78bea7b4-1caf-4528-96e4-ec7f9f43f0db",
 *         programId: "310",
 *         requestId: "{{requestId}}",
 *         txnType: "ANY",
 *         custIfsc: "SBIN0061411",
 *         custAcctNo: "42090969996"
 *     }
 */
export interface VerifyBankAccountRequest {
    /** Pre-configured constant values for different environements */
    entityId: string;
    /** Program id related to this activity. (310 for penny drop) */
    programId: string;
    /**
     * Unique, alphanumeric reference
     * number. Logic in pre-processing script.
     */
    requestId: string;
    /**
     * Defines mode of validation Options: ANY/ IMPS/
     * NACH /UPI/ REVERSE/
     * REVERSE_INTENT
     */
    txnType: string;
    /** Name of account holder to validate. */
    custName?: string;
    /**
     * IFSC of bank account to validate. Required if
     * txnType is other than UPl/ REVERSE
     * / REVERSE_INTENT
     */
    custIfsc?: string;
    /**
     * Account number to validate. Required if txnType is
     * other than UPl/ REVERSE
     * / REVERSE_INTENT
     */
    custAcctNo?: string;
    /**
     * VPA to validate if txnType is UPI
     * Not Required when txnType=REVERSE_INTENT
     */
    custVpa?: string;
    /**
     * Mobile number
     * Required if txnType=UPI and VPA is provided.
     */
    custMobileNo?: string;
    /** Your system reference number for this user */
    trackingRefNo?: string;
    /**
     * The API endpoint where we will submit updates on
     * the validation status for each requestld.
     * Required if txnType is REVERSE/
     * REVERSE_INTENT
     */
    callbackUrl?: string;
}
