// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as SandboxApi from "../index.js";

export class HttpVersionNotSupportedError extends errors.SandboxApiError {
    constructor(body: SandboxApi.ErrorSchema, rawResponse?: core.RawResponse) {
        super({
            message: "HTTPVersionNotSupportedError",
            statusCode: 505,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }
}
