// This file was auto-generated by Fern from our API Definition.

import { ProteanClient } from "./api/resources/protean/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace SandboxApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SandboxApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SandboxApiClient.Options>;
    protected _protean: ProteanClient | undefined;

    constructor(options: SandboxApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get protean(): ProteanClient {
        return (this._protean ??= new ProteanClient(this._options));
    }
}
