// This file was auto-generated by Fern from our API Definition.

import { KycClient } from "./api/resources/kyc/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace SandboxApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SandboxApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SandboxApiClient.Options>;
    protected _kyc: KycClient | undefined;

    constructor(options: SandboxApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get kyc(): KycClient {
        return (this._kyc ??= new KycClient(this._options));
    }
}
